name: python

on: 
  push:
    branches: [ main ]
jobs:
  build:
   runs-on: macos-latest
  steps:
  - name: clone git repo
    uses: actions/checkout@v2

  - name: installing python3
    uses: actions/setup-python@v2
    with:
      python-version: "3.x"
    
  - name: installing dependencies
    run: python -m pip install
    run: pip install -r requirements.txt
    

